In [ ]:
import pandas as pd
import numpy as np

# **Read CSV from GOOGLE DRIVE**

In [ ]:
def read_csv_in_google_drive(url):
    url='https://drive.google.com/uc?id=' + url.split('/')[-2]
    data_frame= pd.read_csv(url, encoding='utf-8')
    return data_frame

In [ ]:
normal_sheet_url='https://drive.google.com/file/d/16L8-2Y6JfA8OMaiNFm4dX2KGk-CP4Lsz/view?usp=sharing'

normal_df = read_csv_in_google_drive(normal_sheet_url)

In [ ]:
normal_df.head()

,cpu_guest,cpu_guest_nice,cpu_idle,cpu_iowait,cpu_irq,cpu_nice,cpu_softirq,cpu_steal,cpu_system,cpu_total,...,processcount_sleeping,processcount_thread,processcount_total,system_hostname,system_hr_name,system_linux_distro,system_os_name,system_os_version,system_platform,timestamp
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,100.0,...,120.0,155.0,122.0,vm1-graph-analytics,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-01-28 19:24:17
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.5,100.0,...,120.0,155.0,122.0,vm1-graph-analytics,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-01-28 19:24:18
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.5,100.0,...,120.0,155.0,122.0,vm1-graph-analytics,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-01-28 19:24:19
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.3,100.0,...,120.0,157.0,122.0,vm1-graph-analytics,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-01-28 19:24:20
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,100.0,...,120.0,155.0,122.0,vm1-graph-analytics,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-01-28 19:24:21

In [ ]:
anormal_sheet_url='https://drive.google.com/file/d/1AXgrm0NvZ-oC1jsPJDiVAde0bn2V03uq/view?usp=share_link'

anormal_df = read_csv_in_google_drive(anormal_sheet_url)

<ipython-input-23-e830945587d0>:3: DtypeWarning: Columns (14,19,26,27,52,57) have mixed types. Specify dtype option on import or set low_memory=False.
  data_frame= pd.read_csv(url, encoding='utf-8')

In [ ]:
anormal_df.head()

,cpu_guest,cpu_guest_nice,cpu_idle,cpu_steal,cpu_iowait,cpu_irq,cpu_nice,cpu_softirq,cpu_system,cpu_total,...,processcount_thread,processcount_total,system_hostname,system_hr_name,system_linux_distro,system_os_name,system_os_version,system_platform,timestamp,flag
0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,154.0,113,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:03,1
1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,154.0,113,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:05,1
2,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,153.0,112,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:06,1
3,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,153.0,112,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:07,1
4,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.0,...,153.0,112,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:08,1

In [ ]:
print(anormal_df.shape)
print(normal_df.shape)

(14461, 83)
(80851, 83)

# **MERGE THE DATASETS**

In [ ]:
anormal_df['flag'] = 1 # 1 for problem
normal_df['flag'] = 0 # 0 for no problem
df = pd.concat([anormal_df, normal_df], axis = 0) # adding the records

In [ ]:
df.head()

,cpu_guest,cpu_guest_nice,cpu_idle,cpu_steal,cpu_iowait,cpu_irq,cpu_nice,cpu_softirq,cpu_system,cpu_total,...,processcount_thread,processcount_total,system_hostname,system_hr_name,system_linux_distro,system_os_name,system_os_version,system_platform,timestamp,flag
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,154.0,113.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:03,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,154.0,113.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:05,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,153.0,112.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:06,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,153.0,112.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:07,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.0,...,153.0,112.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:08,1

# **CREATE CSV FROM DATAFRAME**

In [ ]:
df.to_csv('complete-cryptojack-dataset.csv')

# **READ THE COMPLETE DATASET**

In [ ]:
complete_dataset_url='https://drive.google.com/file/d/1Wy3JP0oz43BvEKC05_JsuLSCLqVH59yB/view?usp=sharing'

df = read_csv_in_google_drive(complete_dataset_url)

<ipython-input-23-e830945587d0>:3: DtypeWarning: Columns (14,19,26,27,52,57) have mixed types. Specify dtype option on import or set low_memory=False.
  data_frame= pd.read_csv(url, encoding='utf-8')

In [ ]:
df.head()

,cpu_guest,cpu_guest_nice,cpu_idle,cpu_steal,cpu_iowait,cpu_irq,cpu_nice,cpu_softirq,cpu_system,cpu_total,...,processcount_thread,processcount_total,system_hostname,system_hr_name,system_linux_distro,system_os_name,system_os_version,system_platform,timestamp,flag
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,154.0,113.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:03,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,154.0,113.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:05,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,153.0,112.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:06,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.0,...,153.0,112.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:07,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.0,...,153.0,112.0,localhost.localdomain,CentOS Linux 7.7.1908 64bit,CentOS Linux 7.7.1908,Linux,3.10.0-1062.12.1.el7.x86_64,64bit,2020-03-20 09:16:08,1